services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/services:/etc/nginx/services:ro
    ports:
      - 81:80
  
  web:
    build: 
      context: ./frontend
    image: beat-roulette:latest

  api:
    build: 
      context: ./backend
    image: beat-roulette-api:latest
    volumes:
      - ./static/:/data
 