name: Build and Push Docker Images to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow only for tags that start with 'v', e.g., v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the 'web' Docker image
      - name: Build and Push Web Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/beat-roulette-web:${{ github.ref_name }} ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/beat-roulette-web:${{ github.ref_name }}

      # Build and push the 'api' Docker image
      - name: Build and Push API Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/beat-roulette-api:${{ github.ref_name }} ./backend
          docker push ghcr.io/${{ github.repository_owner }}/beat-roulette-api:${{ github.ref_name }}
